name: Solar System CI Pipeline v3 "Fixed Artifact Upload"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'features/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-tests:
    name: Run Unit Tests
    strategy:
      matrix:
        node-version: [16, 18, 20]
        operating-system: [ubuntu-latest, macos-latest]
        exclude:
          - node-version: 16
            operating-system: macos-latest

      fail-fast: false

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        # always upload test results, even if tests fail
        if: always()
        with:
          # unique artifact name per matrix job
          name: test-results-${{ matrix.operating-system }}-node${{ matrix.node-version }}
          # path where mocha-junit-reporter actually generates test reports
          path: |
            test-results.xml
            *.xml
            reports/
          if-no-files-found: warn

  code-coverage:
    name: Code Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run code coverage
        continue-on-error: true
        run: npm run coverage

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        # always upload coverage report, even if code coverage step fails, or Code Coverage is Less than Threshold
        if: always()
        with:
          name: code-coverage-report
          path: |
            coverage/
            .nyc_output/
            coverage-summary.json
            cobertura-coverage.xml
          if-no-files-found: warn