name: Solar System CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - features/*

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}


jobs:
    unit-tests:
        name: Run Unit Tests
        strategy:
          matrix:
            node-version: [16, 18, 20]
            operating-system: [ubuntu-latest, macos-latest]
            exclude:
              - node-version: 18
                operating-system: macos-latest

        runs-on: ${{ matrix.operating-system }}

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Node.js V ${{ matrix['node-version'] }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix['node-version'] }}

        - name: Install dependencies
          run: npm install

        - name: Run unit tests
          run: npm test

        - name: Archive Test Results
          uses: actions/upload-artifact@v4.6.2
          with:
            name: test-results
            path: test-results.xml